### ISSUE TITLE
from field is always zero when using expressions parameter

### ISSUE THREAD

**Issue by migolovanov** [starius/luahs#1]
Hello!
I'm trying to use this binding in lua and don't quite understand, why it is working differently in following cases.
There is a code sample
```
local luahs = require("luahs")
local db = luahs.compile {
    expression = '(foo).{1,20}bar',
    flags = luahs.pattern_flags.HS_FLAG_SOM_LEFTMOST,
    mode = luahs.compile_mode.HS_MODE_BLOCK,
}   
scratch = db:makeScratch()
local test=' asdasdsadas foo bar bar'
local hits = db:scan(test,scratch)
```
As result i get `{{from=13,id=0,to=20},{from=13,id=0,to=24}}` and everything seems fine.
But when `expression = '(foo).{1,20}bar',` is replaced with `expressions = { '(foo).{1,20}bar', },`, from field turns into 0: `{{from=0,id=0,to=20},{from=0,id=0,to=24}}`

**Comment by migolovanov** [comment]
Sorry for disturbing, it worked perfect when added flag to each expression.

**Comment by starius** [comment]
Hey

Glad to hear it sorted out. The example is provided in README (look for "If you compile multiple patterns and you need provide flags").

I'm closing the issue.
